name: Build-Deploy-Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AWS_REGION : us-east-1
  HOST : 3.93.63.24
  USERNAME : ec2-user
  PORT : 22

permissions:
      id-token: write   
      contents: read

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ env.HOST }}
        username: ${{ env.USERNAME }}
        key: ${{ secrets.SSH_KEY_DEV }}
        port: ${{ env.PORT }}
        script: |
          echo "========================================================================"
